using System;

namespace TinyEcsBindings.Bevy;

/// <summary>
/// Factory methods for creating systems with ISystemParam parameters.
/// Generated by SystemAdapters.tt
/// </summary>
public static class SystemAdapters
{
    /// <summary>
    /// Create a system from an Action with no parameters.
    /// </summary>
    public static ISystem Create(Action systemFunc)
    {
        return new ParameterizedSystem(Array.Empty<ISystemParam>(), systemFunc);
    }

    /// <summary>
    /// Create a system from an Action with 1 parameter(s).
    /// </summary>
    public static ISystem Create<T0>(Action<T0> systemFunc)
        where T0 : ISystemParam, new()
    {
        var parameters = new ISystemParam[]
        {
            new T0(),
        };

        return new ParameterizedSystem(parameters, () =>
        {
            systemFunc(
                (T0)parameters[0]
            );
        });
    }

    /// <summary>
    /// Create a system from an Action with 2 parameter(s).
    /// </summary>
    public static ISystem Create<T0, T1>(Action<T0, T1> systemFunc)
        where T0 : ISystemParam, new() where T1 : ISystemParam, new()
    {
        var parameters = new ISystemParam[]
        {
            new T0(),
            new T1(),
        };

        return new ParameterizedSystem(parameters, () =>
        {
            systemFunc(
                (T0)parameters[0],
                (T1)parameters[1]
            );
        });
    }

    /// <summary>
    /// Create a system from an Action with 3 parameter(s).
    /// </summary>
    public static ISystem Create<T0, T1, T2>(Action<T0, T1, T2> systemFunc)
        where T0 : ISystemParam, new() where T1 : ISystemParam, new() where T2 : ISystemParam, new()
    {
        var parameters = new ISystemParam[]
        {
            new T0(),
            new T1(),
            new T2(),
        };

        return new ParameterizedSystem(parameters, () =>
        {
            systemFunc(
                (T0)parameters[0],
                (T1)parameters[1],
                (T2)parameters[2]
            );
        });
    }

    /// <summary>
    /// Create a system from an Action with 4 parameter(s).
    /// </summary>
    public static ISystem Create<T0, T1, T2, T3>(Action<T0, T1, T2, T3> systemFunc)
        where T0 : ISystemParam, new() where T1 : ISystemParam, new() where T2 : ISystemParam, new() where T3 : ISystemParam, new()
    {
        var parameters = new ISystemParam[]
        {
            new T0(),
            new T1(),
            new T2(),
            new T3(),
        };

        return new ParameterizedSystem(parameters, () =>
        {
            systemFunc(
                (T0)parameters[0],
                (T1)parameters[1],
                (T2)parameters[2],
                (T3)parameters[3]
            );
        });
    }

    /// <summary>
    /// Create a system from an Action with 5 parameter(s).
    /// </summary>
    public static ISystem Create<T0, T1, T2, T3, T4>(Action<T0, T1, T2, T3, T4> systemFunc)
        where T0 : ISystemParam, new() where T1 : ISystemParam, new() where T2 : ISystemParam, new() where T3 : ISystemParam, new() where T4 : ISystemParam, new()
    {
        var parameters = new ISystemParam[]
        {
            new T0(),
            new T1(),
            new T2(),
            new T3(),
            new T4(),
        };

        return new ParameterizedSystem(parameters, () =>
        {
            systemFunc(
                (T0)parameters[0],
                (T1)parameters[1],
                (T2)parameters[2],
                (T3)parameters[3],
                (T4)parameters[4]
            );
        });
    }

    /// <summary>
    /// Create a system from an Action with 6 parameter(s).
    /// </summary>
    public static ISystem Create<T0, T1, T2, T3, T4, T5>(Action<T0, T1, T2, T3, T4, T5> systemFunc)
        where T0 : ISystemParam, new() where T1 : ISystemParam, new() where T2 : ISystemParam, new() where T3 : ISystemParam, new() where T4 : ISystemParam, new() where T5 : ISystemParam, new()
    {
        var parameters = new ISystemParam[]
        {
            new T0(),
            new T1(),
            new T2(),
            new T3(),
            new T4(),
            new T5(),
        };

        return new ParameterizedSystem(parameters, () =>
        {
            systemFunc(
                (T0)parameters[0],
                (T1)parameters[1],
                (T2)parameters[2],
                (T3)parameters[3],
                (T4)parameters[4],
                (T5)parameters[5]
            );
        });
    }

    /// <summary>
    /// Create a system from an Action with 7 parameter(s).
    /// </summary>
    public static ISystem Create<T0, T1, T2, T3, T4, T5, T6>(Action<T0, T1, T2, T3, T4, T5, T6> systemFunc)
        where T0 : ISystemParam, new() where T1 : ISystemParam, new() where T2 : ISystemParam, new() where T3 : ISystemParam, new() where T4 : ISystemParam, new() where T5 : ISystemParam, new() where T6 : ISystemParam, new()
    {
        var parameters = new ISystemParam[]
        {
            new T0(),
            new T1(),
            new T2(),
            new T3(),
            new T4(),
            new T5(),
            new T6(),
        };

        return new ParameterizedSystem(parameters, () =>
        {
            systemFunc(
                (T0)parameters[0],
                (T1)parameters[1],
                (T2)parameters[2],
                (T3)parameters[3],
                (T4)parameters[4],
                (T5)parameters[5],
                (T6)parameters[6]
            );
        });
    }

    /// <summary>
    /// Create a system from an Action with 8 parameter(s).
    /// </summary>
    public static ISystem Create<T0, T1, T2, T3, T4, T5, T6, T7>(Action<T0, T1, T2, T3, T4, T5, T6, T7> systemFunc)
        where T0 : ISystemParam, new() where T1 : ISystemParam, new() where T2 : ISystemParam, new() where T3 : ISystemParam, new() where T4 : ISystemParam, new() where T5 : ISystemParam, new() where T6 : ISystemParam, new() where T7 : ISystemParam, new()
    {
        var parameters = new ISystemParam[]
        {
            new T0(),
            new T1(),
            new T2(),
            new T3(),
            new T4(),
            new T5(),
            new T6(),
            new T7(),
        };

        return new ParameterizedSystem(parameters, () =>
        {
            systemFunc(
                (T0)parameters[0],
                (T1)parameters[1],
                (T2)parameters[2],
                (T3)parameters[3],
                (T4)parameters[4],
                (T5)parameters[5],
                (T6)parameters[6],
                (T7)parameters[7]
            );
        });
    }

    /// <summary>
    /// Create a system from an Action with 9 parameter(s).
    /// </summary>
    public static ISystem Create<T0, T1, T2, T3, T4, T5, T6, T7, T8>(Action<T0, T1, T2, T3, T4, T5, T6, T7, T8> systemFunc)
        where T0 : ISystemParam, new() where T1 : ISystemParam, new() where T2 : ISystemParam, new() where T3 : ISystemParam, new() where T4 : ISystemParam, new() where T5 : ISystemParam, new() where T6 : ISystemParam, new() where T7 : ISystemParam, new() where T8 : ISystemParam, new()
    {
        var parameters = new ISystemParam[]
        {
            new T0(),
            new T1(),
            new T2(),
            new T3(),
            new T4(),
            new T5(),
            new T6(),
            new T7(),
            new T8(),
        };

        return new ParameterizedSystem(parameters, () =>
        {
            systemFunc(
                (T0)parameters[0],
                (T1)parameters[1],
                (T2)parameters[2],
                (T3)parameters[3],
                (T4)parameters[4],
                (T5)parameters[5],
                (T6)parameters[6],
                (T7)parameters[7],
                (T8)parameters[8]
            );
        });
    }

    /// <summary>
    /// Create a system from an Action with 10 parameter(s).
    /// </summary>
    public static ISystem Create<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9>(Action<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9> systemFunc)
        where T0 : ISystemParam, new() where T1 : ISystemParam, new() where T2 : ISystemParam, new() where T3 : ISystemParam, new() where T4 : ISystemParam, new() where T5 : ISystemParam, new() where T6 : ISystemParam, new() where T7 : ISystemParam, new() where T8 : ISystemParam, new() where T9 : ISystemParam, new()
    {
        var parameters = new ISystemParam[]
        {
            new T0(),
            new T1(),
            new T2(),
            new T3(),
            new T4(),
            new T5(),
            new T6(),
            new T7(),
            new T8(),
            new T9(),
        };

        return new ParameterizedSystem(parameters, () =>
        {
            systemFunc(
                (T0)parameters[0],
                (T1)parameters[1],
                (T2)parameters[2],
                (T3)parameters[3],
                (T4)parameters[4],
                (T5)parameters[5],
                (T6)parameters[6],
                (T7)parameters[7],
                (T8)parameters[8],
                (T9)parameters[9]
            );
        });
    }

    /// <summary>
    /// Create a system from an Action with 11 parameter(s).
    /// </summary>
    public static ISystem Create<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10>(Action<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10> systemFunc)
        where T0 : ISystemParam, new() where T1 : ISystemParam, new() where T2 : ISystemParam, new() where T3 : ISystemParam, new() where T4 : ISystemParam, new() where T5 : ISystemParam, new() where T6 : ISystemParam, new() where T7 : ISystemParam, new() where T8 : ISystemParam, new() where T9 : ISystemParam, new() where T10 : ISystemParam, new()
    {
        var parameters = new ISystemParam[]
        {
            new T0(),
            new T1(),
            new T2(),
            new T3(),
            new T4(),
            new T5(),
            new T6(),
            new T7(),
            new T8(),
            new T9(),
            new T10(),
        };

        return new ParameterizedSystem(parameters, () =>
        {
            systemFunc(
                (T0)parameters[0],
                (T1)parameters[1],
                (T2)parameters[2],
                (T3)parameters[3],
                (T4)parameters[4],
                (T5)parameters[5],
                (T6)parameters[6],
                (T7)parameters[7],
                (T8)parameters[8],
                (T9)parameters[9],
                (T10)parameters[10]
            );
        });
    }

    /// <summary>
    /// Create a system from an Action with 12 parameter(s).
    /// </summary>
    public static ISystem Create<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11>(Action<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11> systemFunc)
        where T0 : ISystemParam, new() where T1 : ISystemParam, new() where T2 : ISystemParam, new() where T3 : ISystemParam, new() where T4 : ISystemParam, new() where T5 : ISystemParam, new() where T6 : ISystemParam, new() where T7 : ISystemParam, new() where T8 : ISystemParam, new() where T9 : ISystemParam, new() where T10 : ISystemParam, new() where T11 : ISystemParam, new()
    {
        var parameters = new ISystemParam[]
        {
            new T0(),
            new T1(),
            new T2(),
            new T3(),
            new T4(),
            new T5(),
            new T6(),
            new T7(),
            new T8(),
            new T9(),
            new T10(),
            new T11(),
        };

        return new ParameterizedSystem(parameters, () =>
        {
            systemFunc(
                (T0)parameters[0],
                (T1)parameters[1],
                (T2)parameters[2],
                (T3)parameters[3],
                (T4)parameters[4],
                (T5)parameters[5],
                (T6)parameters[6],
                (T7)parameters[7],
                (T8)parameters[8],
                (T9)parameters[9],
                (T10)parameters[10],
                (T11)parameters[11]
            );
        });
    }

    /// <summary>
    /// Create a system from an Action with 13 parameter(s).
    /// </summary>
    public static ISystem Create<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12>(Action<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12> systemFunc)
        where T0 : ISystemParam, new() where T1 : ISystemParam, new() where T2 : ISystemParam, new() where T3 : ISystemParam, new() where T4 : ISystemParam, new() where T5 : ISystemParam, new() where T6 : ISystemParam, new() where T7 : ISystemParam, new() where T8 : ISystemParam, new() where T9 : ISystemParam, new() where T10 : ISystemParam, new() where T11 : ISystemParam, new() where T12 : ISystemParam, new()
    {
        var parameters = new ISystemParam[]
        {
            new T0(),
            new T1(),
            new T2(),
            new T3(),
            new T4(),
            new T5(),
            new T6(),
            new T7(),
            new T8(),
            new T9(),
            new T10(),
            new T11(),
            new T12(),
        };

        return new ParameterizedSystem(parameters, () =>
        {
            systemFunc(
                (T0)parameters[0],
                (T1)parameters[1],
                (T2)parameters[2],
                (T3)parameters[3],
                (T4)parameters[4],
                (T5)parameters[5],
                (T6)parameters[6],
                (T7)parameters[7],
                (T8)parameters[8],
                (T9)parameters[9],
                (T10)parameters[10],
                (T11)parameters[11],
                (T12)parameters[12]
            );
        });
    }

    /// <summary>
    /// Create a system from an Action with 14 parameter(s).
    /// </summary>
    public static ISystem Create<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13>(Action<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13> systemFunc)
        where T0 : ISystemParam, new() where T1 : ISystemParam, new() where T2 : ISystemParam, new() where T3 : ISystemParam, new() where T4 : ISystemParam, new() where T5 : ISystemParam, new() where T6 : ISystemParam, new() where T7 : ISystemParam, new() where T8 : ISystemParam, new() where T9 : ISystemParam, new() where T10 : ISystemParam, new() where T11 : ISystemParam, new() where T12 : ISystemParam, new() where T13 : ISystemParam, new()
    {
        var parameters = new ISystemParam[]
        {
            new T0(),
            new T1(),
            new T2(),
            new T3(),
            new T4(),
            new T5(),
            new T6(),
            new T7(),
            new T8(),
            new T9(),
            new T10(),
            new T11(),
            new T12(),
            new T13(),
        };

        return new ParameterizedSystem(parameters, () =>
        {
            systemFunc(
                (T0)parameters[0],
                (T1)parameters[1],
                (T2)parameters[2],
                (T3)parameters[3],
                (T4)parameters[4],
                (T5)parameters[5],
                (T6)parameters[6],
                (T7)parameters[7],
                (T8)parameters[8],
                (T9)parameters[9],
                (T10)parameters[10],
                (T11)parameters[11],
                (T12)parameters[12],
                (T13)parameters[13]
            );
        });
    }

    /// <summary>
    /// Create a system from an Action with 15 parameter(s).
    /// </summary>
    public static ISystem Create<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14>(Action<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14> systemFunc)
        where T0 : ISystemParam, new() where T1 : ISystemParam, new() where T2 : ISystemParam, new() where T3 : ISystemParam, new() where T4 : ISystemParam, new() where T5 : ISystemParam, new() where T6 : ISystemParam, new() where T7 : ISystemParam, new() where T8 : ISystemParam, new() where T9 : ISystemParam, new() where T10 : ISystemParam, new() where T11 : ISystemParam, new() where T12 : ISystemParam, new() where T13 : ISystemParam, new() where T14 : ISystemParam, new()
    {
        var parameters = new ISystemParam[]
        {
            new T0(),
            new T1(),
            new T2(),
            new T3(),
            new T4(),
            new T5(),
            new T6(),
            new T7(),
            new T8(),
            new T9(),
            new T10(),
            new T11(),
            new T12(),
            new T13(),
            new T14(),
        };

        return new ParameterizedSystem(parameters, () =>
        {
            systemFunc(
                (T0)parameters[0],
                (T1)parameters[1],
                (T2)parameters[2],
                (T3)parameters[3],
                (T4)parameters[4],
                (T5)parameters[5],
                (T6)parameters[6],
                (T7)parameters[7],
                (T8)parameters[8],
                (T9)parameters[9],
                (T10)parameters[10],
                (T11)parameters[11],
                (T12)parameters[12],
                (T13)parameters[13],
                (T14)parameters[14]
            );
        });
    }

    /// <summary>
    /// Create a system from an Action with 16 parameter(s).
    /// </summary>
    public static ISystem Create<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15>(Action<T0, T1, T2, T3, T4, T5, T6, T7, T8, T9, T10, T11, T12, T13, T14, T15> systemFunc)
        where T0 : ISystemParam, new() where T1 : ISystemParam, new() where T2 : ISystemParam, new() where T3 : ISystemParam, new() where T4 : ISystemParam, new() where T5 : ISystemParam, new() where T6 : ISystemParam, new() where T7 : ISystemParam, new() where T8 : ISystemParam, new() where T9 : ISystemParam, new() where T10 : ISystemParam, new() where T11 : ISystemParam, new() where T12 : ISystemParam, new() where T13 : ISystemParam, new() where T14 : ISystemParam, new() where T15 : ISystemParam, new()
    {
        var parameters = new ISystemParam[]
        {
            new T0(),
            new T1(),
            new T2(),
            new T3(),
            new T4(),
            new T5(),
            new T6(),
            new T7(),
            new T8(),
            new T9(),
            new T10(),
            new T11(),
            new T12(),
            new T13(),
            new T14(),
            new T15(),
        };

        return new ParameterizedSystem(parameters, () =>
        {
            systemFunc(
                (T0)parameters[0],
                (T1)parameters[1],
                (T2)parameters[2],
                (T3)parameters[3],
                (T4)parameters[4],
                (T5)parameters[5],
                (T6)parameters[6],
                (T7)parameters[7],
                (T8)parameters[8],
                (T9)parameters[9],
                (T10)parameters[10],
                (T11)parameters[11],
                (T12)parameters[12],
                (T13)parameters[13],
                (T14)parameters[14],
                (T15)parameters[15]
            );
        });
    }

}
